import type {
  Team,
  Rep,
  CoachingInsight,
  CoachingSession,
  DataSource,
  TrustSetting,
  TeamSummary,
  PatternShift,
  Manager,
  Tenant,
  Account,
  AccountTouch,
  AccountContact,
  AccountPattern,
} from "@/types"

// ─────────────────────────────────────────────
// Tenant + Manager
// ─────────────────────────────────────────────

export const mockTenant: Tenant = {
  id: "t_01",
  name: "Apex Revenue Co.",
  slug: "apex-revenue",
  plan: "enterprise",
  createdAt: "2024-01-15",
}

export const mockManager: Manager = {
  id: "m_01",
  tenantId: "t_01",
  name: "Jordan Rivera",
  email: "jordan@apexrevenue.com",
  role: "manager",
  teamIds: ["team_01", "team_02"],
}

// ─────────────────────────────────────────────
// Teams
// ─────────────────────────────────────────────

export const mockTeams: Team[] = [
  {
    id: "team_01",
    tenantId: "t_01",
    name: "West Enterprise",
    managerId: "m_01",
    repCount: 8,
    avgPatternMatch: 72,
    avgDriftScore: 28,
    createdAt: "2024-01-15",
  },
  {
    id: "team_02",
    tenantId: "t_01",
    name: "East Mid-Market",
    managerId: "m_01",
    repCount: 6,
    avgPatternMatch: 58,
    avgDriftScore: 42,
    createdAt: "2024-02-01",
  },
]

// ─────────────────────────────────────────────
// Reps
// ─────────────────────────────────────────────

export const mockReps: Rep[] = [
  {
    id: "rep_01",
    tenantId: "t_01",
    teamId: "team_01",
    managerId: "m_01",
    name: "Priya Sharma",
    email: "priya@apexrevenue.com",
    role: "Senior SDR",
    hireDate: "2022-06-01",
    trend: "improving",
    scores: {
      topRepSimilarity: 88,
      workflowDrift: 12,
      prospectingFocusTime: 82,
      followUpDiscipline: 91,
      outboundVelocity: 79,
      signalConfidence: 94,
    },
    recentActivity: generateActivity(180, 28, 85, 45, 60, 40, 45, 22, 95, 22, 0.42, 18, 3.2, 0.88),
    dataSourceIds: ["ds_01", "ds_02", "ds_03"],
  },
  {
    id: "rep_02",
    tenantId: "t_01",
    teamId: "team_01",
    managerId: "m_01",
    name: "Marcus Chen",
    email: "marcus@apexrevenue.com",
    role: "SDR",
    hireDate: "2023-03-15",
    trend: "stable",
    scores: {
      topRepSimilarity: 74,
      workflowDrift: 26,
      prospectingFocusTime: 68,
      followUpDiscipline: 72,
      outboundVelocity: 65,
      signalConfidence: 81,
    },
    recentActivity: generateActivity(150, 18, 72, 38, 55, 35, 40, 28, 78, 18, 0.34, 14, 2.1, 0.71),
    dataSourceIds: ["ds_01", "ds_02"],
  },
  {
    id: "rep_03",
    tenantId: "t_01",
    teamId: "team_01",
    managerId: "m_01",
    name: "Aaliya Torres",
    email: "aaliya@apexrevenue.com",
    role: "SDR",
    hireDate: "2023-08-20",
    trend: "drifting",
    scores: {
      topRepSimilarity: 51,
      workflowDrift: 49,
      prospectingFocusTime: 44,
      followUpDiscipline: 38,
      outboundVelocity: 52,
      signalConfidence: 76,
    },
    recentActivity: generateActivity(95, 12, 55, 28, 45, 25, 60, 48, 48, 12, 0.21, 9, 1.2, 0.44),
    dataSourceIds: ["ds_01", "ds_03"],
  },
  {
    id: "rep_04",
    tenantId: "t_01",
    teamId: "team_01",
    managerId: "m_01",
    name: "Devon Brooks",
    email: "devon@apexrevenue.com",
    role: "Senior SDR",
    hireDate: "2022-01-10",
    trend: "improving",
    scores: {
      topRepSimilarity: 83,
      workflowDrift: 17,
      prospectingFocusTime: 79,
      followUpDiscipline: 84,
      outboundVelocity: 88,
      signalConfidence: 90,
    },
    recentActivity: generateActivity(175, 32, 80, 42, 58, 42, 42, 20, 88, 20, 0.39, 16, 2.8, 0.82),
    dataSourceIds: ["ds_01", "ds_02", "ds_04"],
  },
  {
    id: "rep_05",
    tenantId: "t_01",
    teamId: "team_02",
    managerId: "m_01",
    name: "Sam Nguyen",
    email: "sam@apexrevenue.com",
    role: "SDR",
    hireDate: "2024-01-08",
    trend: "at-risk",
    scores: {
      topRepSimilarity: 34,
      workflowDrift: 66,
      prospectingFocusTime: 29,
      followUpDiscipline: 22,
      outboundVelocity: 31,
      signalConfidence: 62,
    },
    recentActivity: generateActivity(65, 8, 40, 18, 35, 20, 85, 62, 28, 8, 0.14, 6, 0.5, 0.22),
    dataSourceIds: ["ds_01"],
  },
  {
    id: "rep_06",
    tenantId: "t_01",
    teamId: "team_02",
    managerId: "m_01",
    name: "Keisha Owens",
    email: "keisha@apexrevenue.com",
    role: "SDR",
    hireDate: "2023-05-01",
    trend: "stable",
    scores: {
      topRepSimilarity: 67,
      workflowDrift: 33,
      prospectingFocusTime: 71,
      followUpDiscipline: 68,
      outboundVelocity: 60,
      signalConfidence: 78,
    },
    recentActivity: generateActivity(140, 20, 68, 36, 52, 32, 48, 32, 72, 16, 0.31, 13, 1.8, 0.66),
    dataSourceIds: ["ds_01", "ds_02"],
  },
  {
    id: "rep_07",
    tenantId: "t_01",
    teamId: "team_02",
    managerId: "m_01",
    name: "Rafael Diaz",
    email: "rafael@apexrevenue.com",
    role: "Senior SDR",
    hireDate: "2022-09-12",
    trend: "drifting",
    scores: {
      topRepSimilarity: 59,
      workflowDrift: 41,
      prospectingFocusTime: 55,
      followUpDiscipline: 48,
      outboundVelocity: 62,
      signalConfidence: 74,
    },
    recentActivity: generateActivity(120, 16, 62, 32, 48, 28, 55, 42, 58, 14, 0.26, 11, 1.4, 0.52),
    dataSourceIds: ["ds_01", "ds_03"],
  },
]

function generateActivity(
  timeProspecting: number,     // min/day - calls, connects
  timeResearching: number,     // min/day - pre-call prep
  timeInApollo: number,        // min/day 
  timeInLinkedIn: number,      // min/day
  timeInCRM: number,           // min/day
  timeInSequencer: number,     // min/day
  timeInEmail: number,         // min/day
  contextSwitches: number,     // switches/day
  focusBlocksMin: number,      // uninterrupted prospecting min
  calls: number,
  connectRate: number,
  emails: number,
  meetings: number,
  followUpRate: number,
) {
  const days = ["2025-01-06", "2025-01-07", "2025-01-08", "2025-01-09", "2025-01-10"]
  return days.map((date) => ({
    date,
    timeProspecting: Math.round(timeProspecting * (0.85 + Math.random() * 0.3)),
    timeResearching: Math.round(timeResearching * (0.8 + Math.random() * 0.4)),
    timeBuildingLists: Math.round(12 * (0.7 + Math.random() * 0.5)),
    timeInApollo: Math.round(timeInApollo * (0.9 + Math.random() * 0.2)),
    timeInLinkedIn: Math.round(timeInLinkedIn * (0.85 + Math.random() * 0.3)),
    timeInCRM: Math.round(timeInCRM * (0.8 + Math.random() * 0.4)),
    timeInSequencer: Math.round(timeInSequencer * (0.75 + Math.random() * 0.5)),
    timeInEmail: Math.round(timeInEmail * (0.9 + Math.random() * 0.2)),
    timeInCalendar: Math.round(8 * (0.8 + Math.random() * 0.4)),
    idleTime: Math.round(Math.random() * 30),
    contextSwitches: Math.round(contextSwitches * (0.9 + Math.random() * 0.2)),
    focusBlocksMin: Math.round(focusBlocksMin * (0.8 + Math.random() * 0.4)),
    workdayMinutes: 480,
    callsDialed: Math.round(calls * (0.85 + Math.random() * 0.3)),
    connectRate: Math.round(connectRate * 100 * (0.9 + Math.random() * 0.2)),
    emailsSent: Math.round(emails * (0.8 + Math.random() * 0.4)),
    meetingsBooked: Math.round(meetings * (0.7 + Math.random() * 0.6)),
    followUpRate: Math.round(followUpRate * 100 * (0.85 + Math.random() * 0.3)),
  }))
}

// ─────────────────────────────────────────────
// Pattern Shifts
// ─────────────────────────────────────────────

export const mockPatternShifts: PatternShift[] = [
  {
    id: "ps_01",
    repId: "rep_03",
    repName: "Aaliya Torres",
    date: "2025-01-10",
    metric: "followUpDiscipline",
    direction: "down",
    magnitude: 18,
    notes: "Follow-up rate dropped 18% after new sequencer rollout — check if it's capacity or tooling issue",
  },
  {
    id: "ps_02",
    repId: "rep_01",
    repName: "Priya Sharma",
    date: "2025-01-09",
    metric: "topRepSimilarity",
    direction: "up",
    magnitude: 11,
    notes: "Time in prospecting increased 18 min/day — consistent workflow alignment",
  },
  {
    id: "ps_03",
    repId: "rep_05",
    repName: "Sam Nguyen",
    date: "2025-01-10",
    metric: "prospectingFocusTime",
    direction: "down",
    magnitude: 22,
    notes: "Context switches up to 62/day, prospecting focus blocks dropped 35 min — fragmented workflow",
  },
  {
    id: "ps_04",
    repId: "rep_04",
    repName: "Devon Brooks",
    date: "2025-01-08",
    metric: "outboundVelocity",
    direction: "up",
    magnitude: 14,
    notes: "Research time up to 32 min/day avg — spending more time preparing for calls",
  },
  {
    id: "ps_05",
    repId: "rep_07",
    repName: "Rafael Diaz",
    date: "2025-01-07",
    metric: "workflowDrift",
    direction: "down",
    magnitude: 8,
    notes: "Email time normalized, prospecting time stabilized after coaching session",
  },
]

// ─────────────────────────────────────────────
// Coaching Queue
// ─────────────────────────────────────────────

export const mockCoachingInsights: CoachingInsight[] = [
  {
    id: "ci_01",
    tenantId: "t_01",
    repId: "rep_05",
    repName: "Sam Nguyen",
    teamId: "team_02",
    teamName: "East Mid-Market",
    managerId: "m_01",
    severity: "critical",
    status: "new",
    theme: "workflow mix",
    reason: "Spending 85 min/day in email vs 65 min prospecting. Context switches 62/day (2.5x top reps). Workflow structure needs immediate reset.",
    recommendedAction: "Schedule 30-min 1:1 focused on daily workflow blocks. Build time-blocking template together starting with prospecting window.",
    flaggedAt: "2025-01-10T09:00:00Z",
    updatedAt: "2025-01-10T09:00:00Z",
    metrics: { topRepSimilarity: 34, workflowDrift: 66, prospectingFocusTime: 29, followUpDiscipline: 22 },
    notes: [],
  },
  {
    id: "ci_02",
    tenantId: "t_01",
    repId: "rep_03",
    repName: "Aaliya Torres",
    teamId: "team_01",
    teamName: "West Enterprise",
    managerId: "m_01",
    severity: "high",
    status: "reviewing",
    theme: "follow-up discipline",
    reason: "Follow-up discipline dropped from 56 to 38 in 7 days. Correlates with sequencer tool rollout. May be process friction.",
    recommendedAction: "Review sequence cadence and tooling. Is this a capability gap or a setup issue with the new tool?",
    flaggedAt: "2025-01-09T14:00:00Z",
    updatedAt: "2025-01-10T10:30:00Z",
    metrics: { followUpDiscipline: 38, topRepSimilarity: 51 },
    notes: [
      {
        id: "n_01",
        authorId: "m_01",
        authorName: "Jordan Rivera",
        content: "Checked her recent activity — the drop started day 1 of sequencer rollout. She&apos;s spending 60+ min/day in email now vs 35 before. May need hands-on tool training.",
        createdAt: "2025-01-10T10:30:00Z",
      },
    ],
  },
  {
    id: "ci_03",
    tenantId: "t_01",
    repId: "rep_07",
    repName: "Rafael Diaz",
    teamId: "team_02",
    teamName: "East Mid-Market",
    managerId: "m_01",
    severity: "medium",
    status: "watchlist",
    theme: "prospecting focus",
    reason: "Prospecting focus blocks averaging 55 min vs 85+ for top reps. Context switches climbing to 42/day. Focus is fragmenting.",
    recommendedAction: "Discuss morning routine and focus block protection. Recommend quiet hours / DND blocks on calendar.",
    flaggedAt: "2025-01-07T11:00:00Z",
    updatedAt: "2025-01-09T08:00:00Z",
    metrics: { prospectingFocusTime: 55, followUpDiscipline: 48 },
    notes: [],
  },
  {
    id: "ci_04",
    tenantId: "t_01",
    repId: "rep_02",
    repName: "Marcus Chen",
    teamId: "team_01",
    teamName: "West Enterprise",
    managerId: "m_01",
    severity: "medium",
    status: "new",
    theme: "outbound velocity",
    reason: "Research/prep time at 18 min/day vs 28+ for top reps. Spending 72 min in Apollo/LinkedIn — not balanced with research time.",
    recommendedAction: "Share top-performer pre-call checklist. Schedule a co-work session to model research workflow with Priya.",
    flaggedAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
    metrics: { outboundVelocity: 65, topRepSimilarity: 74 },
    notes: [],
  },
  {
    id: "ci_05",
    tenantId: "t_01",
    repId: "rep_06",
    repName: "Keisha Owens",
    teamId: "team_02",
    teamName: "East Mid-Market",
    managerId: "m_01",
    severity: "low",
    status: "coached",
    theme: "winning habits",
    reason: "Top Rep Similarity improving (now 67). Workflow is stabilizing. Good trajectory on prospecting time allocation.",
    recommendedAction: "Acknowledge progress in next 1:1. Identify next focus area — possibly CRM usage optimization.",
    flaggedAt: "2025-01-05T09:00:00Z",
    updatedAt: "2025-01-08T16:00:00Z",
    metrics: { topRepSimilarity: 67, workflowDrift: 33 },
    notes: [
      {
        id: "n_02",
        authorId: "m_01",
        authorName: "Jordan Rivera",
        content: "Great 1:1 — she&apos;s aware of the gaps. We built a daily schedule template and she&apos;s tracking it. Will recheck in 2 weeks.",
        createdAt: "2025-01-08T16:00:00Z",
      },
    ],
  },
]

// ─────────────────────────────────────────────
// Coaching Sessions (Scheduled 1:1s)
// ─────────────────────────────────────────────

const today = new Date()
const todayStr = today.toISOString().split('T')[0]
const tomorrow = new Date(today)
tomorrow.setDate(tomorrow.getDate() + 1)
const tomorrowStr = tomorrow.toISOString().split('T')[0]

export const mockCoachingSessions: CoachingSession[] = [
  {
    id: "cs_01",
    tenantId: "t_01",
    repId: "rep_05",
    repName: "Sam Nguyen",
    managerId: "m_01",
    scheduledAt: `${todayStr}T10:00:00Z`,
    duration: 30,
    status: "scheduled",
    coachingItemId: "ci_01",
    talkingPoints: [
      { id: "tp_01", text: "Review daily workflow structure and time blocks", checked: false },
      { id: "tp_02", text: "Discuss email vs prospecting time balance (85 min vs 65 min)", checked: false },
      { id: "tp_03", text: "Build a time-blocking template together", checked: false },
      { id: "tp_04", text: "Set clear expectations for context switch reduction", checked: false },
    ],
    actionItems: [
      { id: "ai_01", text: "Create morning prospecting block (9-11am)", dueDate: tomorrowStr, completed: false },
      { id: "ai_02", text: "Limit email checks to 3x per day", dueDate: tomorrowStr, completed: false },
    ],
    notes: "",
  },
  {
    id: "cs_02",
    tenantId: "t_01",
    repId: "rep_03",
    repName: "Aaliya Torres",
    managerId: "m_01",
    scheduledAt: `${todayStr}T14:30:00Z`,
    duration: 30,
    status: "scheduled",
    coachingItemId: "ci_02",
    talkingPoints: [
      { id: "tp_05", text: "Understand how sequencer rollout is affecting workflow", checked: false },
      { id: "tp_06", text: "Review follow-up discipline drop (from 56 to 38)", checked: false },
      { id: "tp_07", text: "Identify if this is a training or process issue", checked: false },
    ],
    actionItems: [
      { id: "ai_03", text: "Complete sequencer training module", dueDate: tomorrowStr, completed: false },
    ],
    notes: "",
  },
  {
    id: "cs_03",
    tenantId: "t_01",
    repId: "rep_02",
    repName: "Marcus Chen",
    managerId: "m_01",
    scheduledAt: `${tomorrowStr}T11:00:00Z`,
    duration: 30,
    status: "scheduled",
    coachingItemId: "ci_04",
    talkingPoints: [
      { id: "tp_08", text: "Share top-performer pre-call research checklist", checked: false },
      { id: "tp_09", text: "Discuss balancing research time with outreach volume", checked: false },
    ],
    actionItems: [],
    notes: "",
  },
]

// ─────────────────────────────────────────────
// Rep Targets (Coaching commitments)
// ─────────────────────────────────────────────

export const mockRepTargets: RepTarget[] = [
  {
    id: "rt_01",
    tenantId: "t_01",
    repId: "rep_05",
    createdFromSessionId: "cs_01",
    metric: "prospecting_time",
    targetValue: 300, // 5 hours/day
    timeFrame: "daily",
    notes: "From Jan 10 coaching session — build morning prospecting block 9-11am",
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-10T10:00:00Z",
    status: "active",
  },
  {
    id: "rt_02",
    tenantId: "t_01",
    repId: "rep_05",
    createdFromSessionId: "cs_01",
    metric: "emails_sent",
    targetValue: 18, // max per day (not min)
    timeFrame: "daily",
    notes: "Reduce email time to 3 checks/day max",
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-10T10:00:00Z",
    status: "active",
  },
  {
    id: "rt_03",
    tenantId: "t_01",
    repId: "rep_03",
    metric: "follow_up_rate",
    targetValue: 45, // percentage
    timeFrame: "weekly",
    notes: "Get back to 50+ follow-up rate after sequencer ramp",
    createdAt: "2025-01-08T14:00:00Z",
    updatedAt: "2025-01-10T09:00:00Z",
    status: "active",
  },
  {
    id: "rt_04",
    tenantId: "t_01",
    repId: "rep_02",
    metric: "prospecting_time",
    targetValue: 360, // 6 hours/day target for stronger research
    timeFrame: "daily",
    notes: "Increase research/prep time from 18 to 28 min/day",
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
    status: "active",
  },
  {
    id: "rt_05",
    tenantId: "t_01",
    repId: "rep_06",
    metric: "meetings_booked",
    targetValue: 6, // per week
    timeFrame: "weekly",
    notes: "Maintain momentum from recent coaching",
    createdAt: "2025-01-08T16:00:00Z",
    updatedAt: "2025-01-09T10:00:00Z",
    status: "active",
  },
]

export const mockDataSources = [
  {
    id: "ds_01",
    tenantId: "t_01",
    name: "Salesforce CRM",
    type: "crm",
    provider: "Salesforce",
    status: "connected",
    lastSyncAt: "2025-01-10T06:00:00Z",
    collectsFields: ["Call logs", "Activity timestamps", "Pipeline stage changes", "Email open metadata"],
    doesNotCollect: ["Email body content", "Call recordings", "Personal communications"],
    retentionDays: 90,
  },
  {
    id: "ds_02",
    tenantId: "t_01",
    name: "Google Calendar",
    type: "calendar",
    provider: "Google",
    status: "connected",
    lastSyncAt: "2025-01-10T07:30:00Z",
    collectsFields: ["Meeting duration", "Event count", "Focus block detection", "Prep time signals"],
    doesNotCollect: ["Meeting notes", "Attendee names", "Personal calendar events"],
    retentionDays: 60,
  },
  {
    id: "ds_03",
    tenantId: "t_01",
    name: "Outreach",
    type: "sequencer",
    provider: "Outreach",
    status: "connected",
    lastSyncAt: "2025-01-10T06:45:00Z",
    collectsFields: ["Sequence step completion", "Reply rates", "Follow-up timing", "Task completion"],
    doesNotCollect: ["Email body content", "Contact personal data", "Prospect information"],
    retentionDays: 90,
  },
  {
    id: "ds_04",
    tenantId: "t_01",
    name: "Gong",
    type: "dialer",
    provider: "Gong",
    status: "error",
    lastSyncAt: "2025-01-08T12:00:00Z",
    collectsFields: ["Call count", "Talk time", "Call timing patterns"],
    doesNotCollect: ["Call transcripts", "Call recordings", "Conversation content"],
    retentionDays: 30,
  },
]

// ─────────────────────────────────────────────
// Trust Settings
// ─────────────────────────────────────────────

export const mockTrustSetting: TrustSetting = {
  id: "ts_01",
  tenantId: "t_01",
  retentionDays: 90,
  auditLoggingEnabled: true,
  lastReviewedAt: "2025-01-05",
  reviewedBy: "Jordan Rivera",
  roleAccess: [
    {
      role: "admin",
      canViewIndividualScores: true,
      canViewTeamAggregates: true,
      canViewRawActivity: true,
      canExportData: true,
      canManageSettings: true,
    },
    {
      role: "manager",
      canViewIndividualScores: true,
      canViewTeamAggregates: true,
      canViewRawActivity: false,
      canExportData: true,
      canManageSettings: false,
    },
    {
      role: "viewer",
      canViewIndividualScores: false,
      canViewTeamAggregates: true,
      canViewRawActivity: false,
      canExportData: false,
      canManageSettings: false,
    },
    {
      role: "rep",
      canViewIndividualScores: true,
      canViewTeamAggregates: false,
      canViewRawActivity: false,
      canExportData: false,
      canManageSettings: false,
    },
  ],
}

// ─────────────────────────────────────────────
// Team Summary
// ─────────────────────────────────────────────

export const mockTeamSummary: TeamSummary = {
  totalReps: 14,
  repsDrifting: 3,
  repsImproving: 4,
  coachingOpportunitiesThisWeek: 5,
  avgSignalConfidence: 79,
  patternShifts: mockPatternShifts,
  repsNeedingAttention: mockReps.filter((r) =>
    r.trend === "drifting" || r.trend === "at-risk"
  ),
  topCohortBenchmark: {
    topRepSimilarity: 88,
    workflowDrift: 12,
    prospectingFocusTime: 84,
    followUpDiscipline: 90,
    outboundVelocity: 86,
    signalConfidence: 92,
  },
  teamMedian: {
    topRepSimilarity: 65,
    workflowDrift: 35,
    prospectingFocusTime: 61,
    followUpDiscipline: 60,
    outboundVelocity: 63,
    signalConfidence: 79,
  },
}

// ─────────────────────────────────────────────
// Accounts
// ─────────────────────────────────────────────

export const mockAccounts: Account[] = [
  {
    id: "acc_01",
    tenantId: "t_01",
    name: "Acme Corporation",
    domain: "acme.com",
    industry: "Technology",
    employeeCount: 500,
    annualRevenue: 50000000,
    stage: "evaluation",
    heat: "hot",
    ownerId: "rep_01",
    ownerName: "Priya Sharma",
    createdAt: "2024-11-15",
    lastTouchAt: "2025-01-10T14:30:00Z",
    daysSinceLastTouch: 0,
    totalTouches: 24,
    touchesLast7Days: 6,
    touchesLast30Days: 14,
    meetingsBooked: 4,
    pipelineValue: 85000,
    winProbability: 72,
    contacts: [
      { id: "con_01", accountId: "acc_01", name: "Sarah Chen", title: "VP Engineering", email: "sarah@acme.com", isPrimary: true, touchCount: 12, lastTouchAt: "2025-01-10T14:30:00Z" },
      { id: "con_02", accountId: "acc_01", name: "Mike Ross", title: "Director IT", email: "mike@acme.com", isPrimary: false, touchCount: 8, lastTouchAt: "2025-01-08T11:00:00Z" },
    ],
  },
  {
    id: "acc_02",
    tenantId: "t_01",
    name: "TechStart Inc",
    domain: "techstart.io",
    industry: "SaaS",
    employeeCount: 120,
    annualRevenue: 12000000,
    stage: "discovery",
    heat: "warm",
    ownerId: "rep_01",
    ownerName: "Priya Sharma",
    createdAt: "2024-12-20",
    lastTouchAt: "2025-01-09T09:15:00Z",
    daysSinceLastTouch: 1,
    totalTouches: 8,
    touchesLast7Days: 4,
    touchesLast30Days: 8,
    meetingsBooked: 1,
    pipelineValue: 32000,
    winProbability: 45,
    contacts: [
      { id: "con_03", accountId: "acc_02", name: "Alex Rivera", title: "CTO", email: "alex@techstart.io", isPrimary: true, touchCount: 6, lastTouchAt: "2025-01-09T09:15:00Z" },
    ],
  },
  {
    id: "acc_03",
    tenantId: "t_01",
    name: "Global Dynamics",
    domain: "globaldynamics.com",
    industry: "Manufacturing",
    employeeCount: 2500,
    annualRevenue: 350000000,
    stage: "prospecting",
    heat: "cold",
    ownerId: "rep_02",
    ownerName: "Marcus Chen",
    createdAt: "2025-01-05",
    lastTouchAt: "2025-01-06T10:00:00Z",
    daysSinceLastTouch: 4,
    totalTouches: 3,
    touchesLast7Days: 2,
    touchesLast30Days: 3,
    meetingsBooked: 0,
    pipelineValue: 0,
    winProbability: 15,
    contacts: [
      { id: "con_04", accountId: "acc_03", name: "Jennifer Walsh", title: "Head of Operations", email: "jwalsh@globaldynamics.com", isPrimary: true, touchCount: 2, lastTouchAt: "2025-01-06T10:00:00Z" },
    ],
  },
  {
    id: "acc_04",
    tenantId: "t_01",
    name: "Nexus Financial",
    domain: "nexusfinancial.com",
    industry: "Financial Services",
    employeeCount: 800,
    annualRevenue: 120000000,
    stage: "negotiation",
    heat: "hot",
    ownerId: "rep_04",
    ownerName: "Devon Brooks",
    createdAt: "2024-10-01",
    lastTouchAt: "2025-01-10T16:00:00Z",
    daysSinceLastTouch: 0,
    totalTouches: 42,
    touchesLast7Days: 8,
    touchesLast30Days: 18,
    meetingsBooked: 7,
    pipelineValue: 145000,
    winProbability: 85,
    contacts: [
      { id: "con_05", accountId: "acc_04", name: "David Kim", title: "CFO", email: "dkim@nexusfinancial.com", isPrimary: true, touchCount: 18, lastTouchAt: "2025-01-10T16:00:00Z" },
      { id: "con_06", accountId: "acc_04", name: "Lisa Park", title: "VP Finance", email: "lpark@nexusfinancial.com", isPrimary: false, touchCount: 14, lastTouchAt: "2025-01-09T14:00:00Z" },
      { id: "con_07", accountId: "acc_04", name: "Tom Bradley", title: "IT Director", email: "tbradley@nexusfinancial.com", isPrimary: false, touchCount: 10, lastTouchAt: "2025-01-08T11:30:00Z" },
    ],
  },
  {
    id: "acc_05",
    tenantId: "t_01",
    name: "CloudScale Systems",
    domain: "cloudscale.io",
    industry: "Cloud Infrastructure",
    employeeCount: 350,
    annualRevenue: 45000000,
    stage: "closed-won",
    heat: "hot",
    ownerId: "rep_01",
    ownerName: "Priya Sharma",
    createdAt: "2024-08-15",
    lastTouchAt: "2025-01-08T10:00:00Z",
    daysSinceLastTouch: 2,
    totalTouches: 38,
    touchesLast7Days: 2,
    touchesLast30Days: 8,
    meetingsBooked: 8,
    pipelineValue: 95000,
    winProbability: 100,
    contacts: [
      { id: "con_08", accountId: "acc_05", name: "Rachel Green", title: "CEO", email: "rachel@cloudscale.io", isPrimary: true, touchCount: 22, lastTouchAt: "2025-01-08T10:00:00Z" },
      { id: "con_09", accountId: "acc_05", name: "James Miller", title: "CTO", email: "james@cloudscale.io", isPrimary: false, touchCount: 16, lastTouchAt: "2025-01-07T15:00:00Z" },
    ],
  },
  {
    id: "acc_06",
    tenantId: "t_01",
    name: "Retail Plus",
    domain: "retailplus.com",
    industry: "Retail",
    employeeCount: 1200,
    annualRevenue: 180000000,
    stage: "prospecting",
    heat: "warm",
    ownerId: "rep_03",
    ownerName: "Aaliya Torres",
    createdAt: "2025-01-02",
    lastTouchAt: "2025-01-07T11:00:00Z",
    daysSinceLastTouch: 3,
    totalTouches: 5,
    touchesLast7Days: 4,
    touchesLast30Days: 5,
    meetingsBooked: 0,
    pipelineValue: 0,
    winProbability: 25,
    contacts: [
      { id: "con_10", accountId: "acc_06", name: "Emma Thompson", title: "Head of Digital", email: "ethompson@retailplus.com", isPrimary: true, touchCount: 4, lastTouchAt: "2025-01-07T11:00:00Z" },
    ],
  },
  {
    id: "acc_07",
    tenantId: "t_01",
    name: "HealthTech Solutions",
    domain: "healthtechsol.com",
    industry: "Healthcare",
    employeeCount: 650,
    annualRevenue: 85000000,
    stage: "discovery",
    heat: "cold",
    ownerId: "rep_05",
    ownerName: "Sam Nguyen",
    createdAt: "2024-12-10",
    lastTouchAt: "2024-12-28T14:00:00Z",
    daysSinceLastTouch: 13,
    totalTouches: 4,
    touchesLast7Days: 0,
    touchesLast30Days: 2,
    meetingsBooked: 1,
    pipelineValue: 55000,
    winProbability: 20,
    contacts: [
      { id: "con_11", accountId: "acc_07", name: "Dr. Patricia Lane", title: "CMIO", email: "plane@healthtechsol.com", isPrimary: true, touchCount: 3, lastTouchAt: "2024-12-28T14:00:00Z" },
    ],
  },
  {
    id: "acc_08",
    tenantId: "t_01",
    name: "Metro Logistics",
    domain: "metrologistics.com",
    industry: "Logistics",
    employeeCount: 3000,
    annualRevenue: 420000000,
    stage: "evaluation",
    heat: "warm",
    ownerId: "rep_06",
    ownerName: "Keisha Owens",
    createdAt: "2024-11-20",
    lastTouchAt: "2025-01-09T16:30:00Z",
    daysSinceLastTouch: 1,
    totalTouches: 16,
    touchesLast7Days: 5,
    touchesLast30Days: 10,
    meetingsBooked: 3,
    pipelineValue: 125000,
    winProbability: 55,
    contacts: [
      { id: "con_12", accountId: "acc_08", name: "Robert Chen", title: "COO", email: "rchen@metrologistics.com", isPrimary: true, touchCount: 10, lastTouchAt: "2025-01-09T16:30:00Z" },
      { id: "con_13", accountId: "acc_08", name: "Maria Santos", title: "VP Technology", email: "msantos@metrologistics.com", isPrimary: false, touchCount: 6, lastTouchAt: "2025-01-08T09:00:00Z" },
    ],
  },
  {
    id: "acc_09",
    tenantId: "t_01",
    name: "EduLearn Platform",
    domain: "edulearn.com",
    industry: "EdTech",
    employeeCount: 200,
    annualRevenue: 25000000,
    stage: "closed-lost",
    heat: "cold",
    ownerId: "rep_07",
    ownerName: "Rafael Diaz",
    createdAt: "2024-09-01",
    lastTouchAt: "2024-12-15T10:00:00Z",
    daysSinceLastTouch: 26,
    totalTouches: 22,
    touchesLast7Days: 0,
    touchesLast30Days: 0,
    meetingsBooked: 4,
    pipelineValue: 0,
    winProbability: 0,
    contacts: [
      { id: "con_14", accountId: "acc_09", name: "Jessica Adams", title: "CEO", email: "jadams@edulearn.com", isPrimary: true, touchCount: 14, lastTouchAt: "2024-12-15T10:00:00Z" },
    ],
  },
  {
    id: "acc_10",
    tenantId: "t_01",
    name: "DataCore Analytics",
    domain: "datacore.ai",
    industry: "Analytics",
    employeeCount: 180,
    annualRevenue: 22000000,
    stage: "discovery",
    heat: "hot",
    ownerId: "rep_04",
    ownerName: "Devon Brooks",
    createdAt: "2025-01-03",
    lastTouchAt: "2025-01-10T11:00:00Z",
    daysSinceLastTouch: 0,
    totalTouches: 9,
    touchesLast7Days: 7,
    touchesLast30Days: 9,
    meetingsBooked: 2,
    pipelineValue: 48000,
    winProbability: 60,
    contacts: [
      { id: "con_15", accountId: "acc_10", name: "Nathan Lee", title: "VP Data", email: "nlee@datacore.ai", isPrimary: true, touchCount: 7, lastTouchAt: "2025-01-10T11:00:00Z" },
      { id: "con_16", accountId: "acc_10", name: "Amanda Foster", title: "Head of Analytics", email: "afoster@datacore.ai", isPrimary: false, touchCount: 2, lastTouchAt: "2025-01-09T14:00:00Z" },
    ],
  },
]

// ─────────────────────────────────────────────
// Account Touches (Timeline)
// ─────────────────────────────────────────────

export const mockAccountTouches: AccountTouch[] = [
  // Acme Corporation (acc_01) - hot evaluation account with Priya
  { id: "touch_01", accountId: "acc_01", contactId: "con_01", repId: "rep_01", repName: "Priya Sharma", channel: "email", direction: "outbound", outcome: "positive", subject: "Follow-up on pricing discussion", timestamp: "2025-01-10T14:30:00Z", nextStepScheduled: true },
  { id: "touch_02", accountId: "acc_01", contactId: "con_01", repId: "rep_01", repName: "Priya Sharma", channel: "meeting", direction: "outbound", outcome: "meeting_booked", subject: "Demo with engineering team", timestamp: "2025-01-09T10:00:00Z", durationMinutes: 45, nextStepScheduled: true },
  { id: "touch_03", accountId: "acc_01", contactId: "con_02", repId: "rep_01", repName: "Priya Sharma", channel: "call", direction: "outbound", outcome: "positive", subject: "Technical requirements review", timestamp: "2025-01-08T11:00:00Z", durationMinutes: 20, nextStepScheduled: true },
  { id: "touch_04", accountId: "acc_01", contactId: "con_01", repId: "rep_01", repName: "Priya Sharma", channel: "linkedin", direction: "outbound", outcome: "positive", subject: "Connected and shared case study", timestamp: "2025-01-07T09:00:00Z", nextStepScheduled: false },
  { id: "touch_05", accountId: "acc_01", contactId: "con_01", repId: "rep_01", repName: "Priya Sharma", channel: "email", direction: "inbound", outcome: "positive", subject: "Re: Pricing proposal", timestamp: "2025-01-06T16:00:00Z", nextStepScheduled: true },
  { id: "touch_06", accountId: "acc_01", contactId: "con_01", repId: "rep_01", repName: "Priya Sharma", channel: "email", direction: "outbound", outcome: "deal_moved", subject: "Pricing proposal attached", timestamp: "2025-01-05T14:00:00Z", nextStepScheduled: true },

  // Nexus Financial (acc_04) - hot negotiation account with Devon
  { id: "touch_07", accountId: "acc_04", contactId: "con_05", repId: "rep_04", repName: "Devon Brooks", channel: "meeting", direction: "outbound", outcome: "deal_moved", subject: "Contract review meeting", timestamp: "2025-01-10T16:00:00Z", durationMinutes: 60, nextStepScheduled: true },
  { id: "touch_08", accountId: "acc_04", contactId: "con_06", repId: "rep_04", repName: "Devon Brooks", channel: "call", direction: "outbound", outcome: "positive", subject: "Addressed budget concerns", timestamp: "2025-01-09T14:00:00Z", durationMinutes: 25, nextStepScheduled: true },
  { id: "touch_09", accountId: "acc_04", contactId: "con_07", repId: "rep_04", repName: "Devon Brooks", channel: "email", direction: "outbound", outcome: "positive", subject: "Technical specs document", timestamp: "2025-01-08T11:30:00Z", nextStepScheduled: false },
  { id: "touch_10", accountId: "acc_04", contactId: "con_05", repId: "rep_04", repName: "Devon Brooks", channel: "meeting", direction: "outbound", outcome: "meeting_booked", subject: "Executive presentation", timestamp: "2025-01-07T10:00:00Z", durationMinutes: 45, nextStepScheduled: true },

  // DataCore Analytics (acc_10) - hot discovery account with Devon
  { id: "touch_11", accountId: "acc_10", contactId: "con_15", repId: "rep_04", repName: "Devon Brooks", channel: "call", direction: "outbound", outcome: "positive", subject: "Needs assessment call", timestamp: "2025-01-10T11:00:00Z", durationMinutes: 30, nextStepScheduled: true },
  { id: "touch_12", accountId: "acc_10", contactId: "con_15", repId: "rep_04", repName: "Devon Brooks", channel: "email", direction: "outbound", outcome: "positive", subject: "Case study: Analytics company", timestamp: "2025-01-09T14:00:00Z", nextStepScheduled: true },
  { id: "touch_13", accountId: "acc_10", contactId: "con_16", repId: "rep_04", repName: "Devon Brooks", channel: "linkedin", direction: "outbound", outcome: "positive", subject: "Introduction message", timestamp: "2025-01-09T09:00:00Z", nextStepScheduled: false },

  // HealthTech Solutions (acc_07) - cold discovery with Sam (needs attention)
  { id: "touch_14", accountId: "acc_07", contactId: "con_11", repId: "rep_05", repName: "Sam Nguyen", channel: "meeting", direction: "outbound", outcome: "neutral", subject: "Initial discovery call", timestamp: "2024-12-28T14:00:00Z", durationMinutes: 30, nextStepScheduled: false },
  { id: "touch_15", accountId: "acc_07", contactId: "con_11", repId: "rep_05", repName: "Sam Nguyen", channel: "email", direction: "outbound", outcome: "no_response", subject: "Following up on our call", timestamp: "2024-12-30T10:00:00Z", nextStepScheduled: false },

  // Metro Logistics (acc_08) - warm evaluation with Keisha
  { id: "touch_16", accountId: "acc_08", contactId: "con_12", repId: "rep_06", repName: "Keisha Owens", channel: "meeting", direction: "outbound", outcome: "deal_moved", subject: "Stakeholder alignment meeting", timestamp: "2025-01-09T16:30:00Z", durationMinutes: 45, nextStepScheduled: true },
  { id: "touch_17", accountId: "acc_08", contactId: "con_13", repId: "rep_06", repName: "Keisha Owens", channel: "call", direction: "outbound", outcome: "positive", subject: "Technical requirements", timestamp: "2025-01-08T09:00:00Z", durationMinutes: 20, nextStepScheduled: true },
  { id: "touch_18", accountId: "acc_08", contactId: "con_12", repId: "rep_06", repName: "Keisha Owens", channel: "email", direction: "inbound", outcome: "positive", subject: "Re: Proposal questions", timestamp: "2025-01-07T14:00:00Z", nextStepScheduled: true },
]

// ─────────────────────────────────────────────
// Account Patterns (Rep-level winning sequences)
// ─────────────────────────────────────────────

export const mockAccountPatterns: AccountPattern[] = [
  {
    repId: "rep_01",
    repName: "Priya Sharma",
    avgTouchesToMeeting: 4.2,
    avgDaysToMeeting: 8,
    preferredChannelMix: { email: 45, call: 25, linkedin: 20, meeting: 10, sms: 0 },
    avgTouchesPerWeek: 5.8,
    conversionRate: 28,
    winRate: 42,
  },
  {
    repId: "rep_04",
    repName: "Devon Brooks",
    avgTouchesToMeeting: 3.8,
    avgDaysToMeeting: 6,
    preferredChannelMix: { email: 35, call: 35, linkedin: 15, meeting: 15, sms: 0 },
    avgTouchesPerWeek: 6.5,
    conversionRate: 32,
    winRate: 48,
  },
  {
    repId: "rep_02",
    repName: "Marcus Chen",
    avgTouchesToMeeting: 5.5,
    avgDaysToMeeting: 12,
    preferredChannelMix: { email: 55, call: 20, linkedin: 15, meeting: 10, sms: 0 },
    avgTouchesPerWeek: 4.2,
    conversionRate: 18,
    winRate: 28,
  },
  {
    repId: "rep_03",
    repName: "Aaliya Torres",
    avgTouchesToMeeting: 6.2,
    avgDaysToMeeting: 14,
    preferredChannelMix: { email: 60, call: 15, linkedin: 20, meeting: 5, sms: 0 },
    avgTouchesPerWeek: 3.8,
    conversionRate: 14,
    winRate: 22,
  },
  {
    repId: "rep_05",
    repName: "Sam Nguyen",
    avgTouchesToMeeting: 7.5,
    avgDaysToMeeting: 18,
    preferredChannelMix: { email: 70, call: 10, linkedin: 15, meeting: 5, sms: 0 },
    avgTouchesPerWeek: 2.8,
    conversionRate: 8,
    winRate: 12,
  },
  {
    repId: "rep_06",
    repName: "Keisha Owens",
    avgTouchesToMeeting: 4.8,
    avgDaysToMeeting: 10,
    preferredChannelMix: { email: 40, call: 30, linkedin: 15, meeting: 15, sms: 0 },
    avgTouchesPerWeek: 5.2,
    conversionRate: 24,
    winRate: 35,
  },
  {
    repId: "rep_07",
    repName: "Rafael Diaz",
    avgTouchesToMeeting: 5.8,
    avgDaysToMeeting: 13,
    preferredChannelMix: { email: 50, call: 25, linkedin: 15, meeting: 10, sms: 0 },
    avgTouchesPerWeek: 4.0,
    conversionRate: 16,
    winRate: 25,
  },
]
